### ISSUE TITLE
Machine Learning Library Reasearch

### ISSUE THREAD

**Issue by kren1** [group-24/Palpitate#2]
Incorporate a machine learning library in our build system. Make a test case that uses it to learn something trivial to illustrate how to work with it. It would also be nice to have examples for different ML tecniques.

**Comment by michaelcypher** [comment]
It's worth noting, ML does not need to be done in Java (I believe gradle also supports C/C++).

**Comment by kren1** [comment]
I think gradle supports anything if you write custom scripts. So no need to limit ourselves to anything, java would just be the most convinient...
